In [19]:
import numpy as np
import math
from itertools import combinations, permutations, combinations_with_replacement

In [3]:
list(permutations(range(10)))

[(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
 (0, 1, 2, 3, 4, 5, 6, 7, 9, 8),
 (0, 1, 2, 3, 4, 5, 6, 8, 7, 9),
 (0, 1, 2, 3, 4, 5, 6, 8, 9, 7),
 (0, 1, 2, 3, 4, 5, 6, 9, 7, 8),
 (0, 1, 2, 3, 4, 5, 6, 9, 8, 7),
 (0, 1, 2, 3, 4, 5, 7, 6, 8, 9),
 (0, 1, 2, 3, 4, 5, 7, 6, 9, 8),
 (0, 1, 2, 3, 4, 5, 7, 8, 6, 9),
 (0, 1, 2, 3, 4, 5, 7, 8, 9, 6),
 (0, 1, 2, 3, 4, 5, 7, 9, 6, 8),
 (0, 1, 2, 3, 4, 5, 7, 9, 8, 6),
 (0, 1, 2, 3, 4, 5, 8, 6, 7, 9),
 (0, 1, 2, 3, 4, 5, 8, 6, 9, 7),
 (0, 1, 2, 3, 4, 5, 8, 7, 6, 9),
 (0, 1, 2, 3, 4, 5, 8, 7, 9, 6),
 (0, 1, 2, 3, 4, 5, 8, 9, 6, 7),
 (0, 1, 2, 3, 4, 5, 8, 9, 7, 6),
 (0, 1, 2, 3, 4, 5, 9, 6, 7, 8),
 (0, 1, 2, 3, 4, 5, 9, 6, 8, 7),
 (0, 1, 2, 3, 4, 5, 9, 7, 6, 8),
 (0, 1, 2, 3, 4, 5, 9, 7, 8, 6),
 (0, 1, 2, 3, 4, 5, 9, 8, 6, 7),
 (0, 1, 2, 3, 4, 5, 9, 8, 7, 6),
 (0, 1, 2, 3, 4, 6, 5, 7, 8, 9),
 (0, 1, 2, 3, 4, 6, 5, 7, 9, 8),
 (0, 1, 2, 3, 4, 6, 5, 8, 7, 9),
 (0, 1, 2, 3, 4, 6, 5, 8, 9, 7),
 (0, 1, 2, 3, 4, 6, 5, 9, 7, 8),
 (0, 1, 2, 3, 4, 6, 5, 9, 8, 7),
 (0, 1, 2,

In [8]:
list(permutations(['hi', 'bye', 'sigh'])


SyntaxError: unexpected EOF while parsing (<ipython-input-8-3f13aa8b1578>, line 1)

In [9]:
combinations(set('abcdefgh'), 5)

In [12]:
len(list(permutations(set('abcdefgh'), 5)))

6720

In [13]:
len(list(combinations_with_replacement(set('abcdefgh'), 5)))

792

In [14]:
from math import factorial

In [15]:
factorial(5)

120

In [21]:
math.pi

3.141592653589793

In [22]:
l = [2,4,6,8]

In [23]:
type(l)

list

In [24]:
print(l)

[2, 4, 6, 8]


In [25]:
l_arr = np.array(l)

In [26]:
l_arr

array([2, 4, 6, 8])

In [27]:
range(10)

range(0, 10)

In [29]:
np.arange(0, 100, 2)   # Specify every 2 integers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
example_arr = np.arange(0, 100, 2).reshape(10, 5)  # Reshaped the data in 10 rows of 5 cols

In [32]:
example_arr ** 2


array([[   0,    4,   16,   36,   64],
       [ 100,  144,  196,  256,  324],
       [ 400,  484,  576,  676,  784],
       [ 900, 1024, 1156, 1296, 1444],
       [1600, 1764, 1936, 2116, 2304],
       [2500, 2704, 2916, 3136, 3364],
       [3600, 3844, 4096, 4356, 4624],
       [4900, 5184, 5476, 5776, 6084],
       [6400, 6724, 7056, 7396, 7744],
       [8100, 8464, 8836, 9216, 9604]])

In [33]:
example_arr.shape

(10, 5)

In [37]:
ex_arr_reshaped = np.arange(2,200,3).reshape(11,6)

In [39]:
ex_arr_reshaped[4:]

array([[ 74,  77,  80,  83,  86,  89],
       [ 92,  95,  98, 101, 104, 107],
       [110, 113, 116, 119, 122, 125],
       [128, 131, 134, 137, 140, 143],
       [146, 149, 152, 155, 158, 161],
       [164, 167, 170, 173, 176, 179],
       [182, 185, 188, 191, 194, 197]])

In [40]:
ex_arr_reshaped[: , 3] # Grabs the 3rd column

array([ 11,  29,  47,  65,  83, 101, 119, 137, 155, 173, 191])

In [41]:
ex_arr_reshaped

array([[  2,   5,   8,  11,  14,  17],
       [ 20,  23,  26,  29,  32,  35],
       [ 38,  41,  44,  47,  50,  53],
       [ 56,  59,  62,  65,  68,  71],
       [ 74,  77,  80,  83,  86,  89],
       [ 92,  95,  98, 101, 104, 107],
       [110, 113, 116, 119, 122, 125],
       [128, 131, 134, 137, 140, 143],
       [146, 149, 152, 155, 158, 161],
       [164, 167, 170, 173, 176, 179],
       [182, 185, 188, 191, 194, 197]])

In [42]:
ex_arr_reshaped[:4 , 3]  # First four elements of third column

array([11, 29, 47, 65])

In [43]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.full(16, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.full(16, 0).reshape(4,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
a1, a2 = np.array([3,4]), np.array([5,6])

In [48]:
np.dot(a1, a2)  # Matrix dot product

39

In [49]:
# 3 * vector -- is "broadcasting" in numpy..  vectorized
a1 @ a2

39

In [50]:
l1 = [2, 4, 6, 8]
l2 = [4, 5]

In [51]:
l1 + l2

[2, 4, 6, 8, 4, 5]

In [52]:
np.array(l1) * 5

array([10, 20, 30, 40])

In [53]:
np.array(l1) + 5


array([ 7,  9, 11, 13])

In [55]:
# can add (+) two arrays
mat1 = np.array([[1, 2, 3],[4, 5, 6]])
mat2 = np.array([1, 0, 1])
mat1 + mat2

array([[2, 2, 4],
       [5, 5, 7]])

In [57]:
np.random.seed(1000)

In [59]:
d = np.random.random(10)
d

array([0.20708234, 0.74246953, 0.39215413, 0.18225652, 0.74353941,
       0.06958208, 0.8853372 , 0.9526444 , 0.93114343, 0.41543095])

In [64]:
np.random.seed(1000)
randarray = np.random.randn(10)  # Sample from a standard normal distribution
randarray.reshape(-1, 1)
randarray.T   # Transpose. But a vector is a 1-D array

array([-0.8044583 ,  0.32093155, -0.02548288,  0.64432383, -0.30079667,
        0.38947455, -0.1074373 , -0.47998308,  0.5950355 , -0.46466753])

In [75]:
np.random.seed(1000)
n, p = 1, 0.5
s = np.random.binomial(n, p, 10)


In [76]:
sum(s)/10

0.4

In [77]:
%%timeit 
s2 = np.random.binomial(n, p, 10000)
np.mean(s2)

316 µs ± 21.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
