In [38]:
import numpy as np
from scipy.stats import norm, chisquare
import matplotlib.pyplot as plt

In [2]:
np.diff([1, 1, 2, 5, 6], n=1)

array([0, 1, 3, 1])

In [34]:
x_values = [float("-Inf"), 67.5, 72.5, 77.5, 82.5, float("Inf")]
m = 77.04
s = 6.695
num_obs = 103   # Number of observations
# loc is mean, scale is stdev
cdfs = norm.cdf(x_values, loc=m, scale=s)
diff_cdf = np.diff(cdfs, n=1)
print(f"cdfs: {cdfs}")
print(f"diff_cdf: {diff_cdf}")
res = diff_pdf*num_obs
print(f"res: {res}")

cdfs: [0.         0.0770867  0.24884844 0.52738897 0.79261664 1.        ]
diff_cdf: [0.0770867  0.17176174 0.27854053 0.26522767 0.20738336]
res: [ 7.93992973 17.69145957 28.68967474 27.31844977 21.36048618]


In [29]:
# Correct answer is: 7.93993 17.69146 28.68967 27.31845 21.36049
res

array([ 7.93992973, 17.69145957, 28.68967474, 27.31844977, 21.36048618])

In [37]:
observed = np.asarray([8, 18, 27, 25, 25])
observed

array([ 8, 18, 27, 25, 25])

In [41]:
# Q =  0.9222296
chisquare(observed, res, ddof=1)

Power_divergenceResult(statistic=0.9222295738740289, pvalue=0.8200602562569497)